spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/v1/users/**
          filters:


        - id: uploader-service
          uri: lb://uploader-service
          predicates:
            - Path=/v1/doc/**
          filters:

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/v1/auth/**
          filters:

        - id: security
          uri: lb://security
          predicates:
            - Path=/v1/auth/**
          filters:



      discovery:
        locator:
          enabled: true

server:
  port: 8888

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
