spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: auth-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri:
server:
  port: 9001


jwt:
  secret: 33527944527a4459703966584d6a4d7847757542487868587653676e74636755
  expiration: 86400
