spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: security
  profiles:
    active: production

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_eBfoUwDpL"
server:
  port: 9090


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days